# Generated by Django 4.2.6 on 2023-10-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfoption',
            old_name='option_name',
            new_name='option_value',
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.tflayertype'),
        ),
        migrations.AlterField(
            model_name='neuralnetworkconfig',
            name='next_neural_network',
            field=models.ManyToManyField(blank=True, related_name='link_next_neural_network', to='src.neuralnetworkconfig'),
        ),
        migrations.AlterField(
            model_name='neuralnetworkconfig',
            name='previous_neural_network',
            field=models.ManyToManyField(blank=True, related_name='link_previous_neural_network', to='src.neuralnetworkconfig'),
        ),
        migrations.AlterField(
            model_name='tfoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.tflayertypeoption'),
        ),
    ]
