# Generated by Django 4.2.6 on 2023-10-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CortexV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
            ],
        ),
        migrations.RenameField(
            model_name='tfoption',
            old_name='option_name',
            new_name='option_value',
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.tflayertype'),
        ),
        migrations.AlterField(
            model_name='neuralnetworkconfig',
            name='next_neural_network',
            field=models.ManyToManyField(blank=True, related_name='link_next_neural_network', to='src.neuralnetworkconfig'),
        ),
        migrations.AlterField(
            model_name='neuralnetworkconfig',
            name='previous_neural_network',
            field=models.ManyToManyField(blank=True, related_name='link_previous_neural_network', to='src.neuralnetworkconfig'),
        ),
        migrations.AlterField(
            model_name='tfoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.tflayertypeoption'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.cortexv2')),
                ('from_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_network', to='src.neuralnetwork')),
                ('to_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_network', to='src.neuralnetwork')),
            ],
        ),
    ]
