# Generated by Django 4.2.6 on 2023-10-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_rename_option_name_tfoption_option_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='options',
        ),
        migrations.RemoveField(
            model_name='neuralnetwork',
            name='layers',
        ),
        migrations.AddField(
            model_name='layer',
            name='neural_network_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='src.neuralnetwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layer',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfoption',
            name='layer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='src.layer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.TextField(),
        ),
    ]
