# Generated by Django 4.2.6 on 2023-10-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_remove_layer_options_remove_neuralnetwork_layers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='neural_network_id',
            new_name='neural_network',
        ),
        migrations.RenameField(
            model_name='tfoption',
            old_name='layer_id',
            new_name='layer',
        ),
    ]
