# Generated by Django 4.2.6 on 2023-10-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_cortexv2_rename_option_name_tfoption_option_value_and_more'),
        ('src', '0004_rename_neural_network_id_layer_neural_network_and_more'),
    ]

    operations = [
    ]
